### ISSUE TITLE
rtcpMode not working for iOS react-native

### ISSUE THREAD

**Issue by jfan-dolby** [voxeet/voxeet-uxkit-reactnative#14]
Copied from internal tracking ticket CC-374.

> When creating a conference in iOS, I am unable to set a value for rtcpMode. In the logs it appears as rtcpMode: N/A. It works on Android.

> Using voxeet-uxkit-reactnative: 0.1.32

> it looks like it has never worked for iOS, only for Android. We are using voxeet-uxkit-reactnative v 0.1.32 which is using v 2.4.0 of the SDK but it was happening in earlier versions as well.

**Comment by VTCoco** [comment]
Fixed with https://github.com/voxeet/voxeet-uxkit-reactnative/releases/tag/v0.1.33
