### ISSUE TITLE
Broken link to Android SDK Sample in read me

### ISSUE THREAD

**Issue by techiespace** [voxeet/voxeet-uxkit-reactnative#18]
**Describe the bug**

Android SDK Sample link in README.md is broken 

**Expected Behaviour**

Point to the correct sample repo

**Steps to Reproduce the Problem**

  1. Go to https://github.com/voxeet/voxeet-uxkit-reactnative
  2. Click on Android SDK Sample link in README.md
  3. The link redirects to a 404 page

**Comment by FabienLavocat** [comment]
Thank you, this link has been removed in the coming version of the UXKit for React Native.
