### ISSUE TITLE
Video conference by default

### ISSUE THREAD

**Issue by tuneerclixlogix** [voxeet/voxeet-uxkit-reactnative#26]
Question: Can we start the conference with the video On by default and the other user will also be notified that its an audio or video conference ?

**Comment by FabienLavocat** [comment]
Yes, you can start the conference with video on by default:
```
const constraints = {
  audio: true,
  video: true,
};

let createConference = await VoxeetSDK.create({ params: { dolbyVoice: true } });
await VoxeetSDK.join(createConference.conferenceId, { constraints: constraints });
```

Unfortunately, there is no way to let the other participant know the audio & video are on with the UXKit.

**Comment by tuneerclixlogix** [comment]
@FabienLavocat I tried with 
const constraints = {
          audio: true,
          video: true,
};
but still I have to manually switch to video mode

**Comment by FabienLavocat** [comment]
@tuneerclixlogix on both iOS and Android?

**Comment by codlab** [comment]
It's currently the expected behavior, those options are not implemented. (for reference : https://github.com/voxeet/voxeet-uxkit-reactnative/blob/master/lib/types/JoinConference.ts)

To activate the video, it's either possible using the `VoxeetSDK.defaultVideo(enable: boolean)` or using the new beta version (or direct integration of the new branch in the project)

**Comment by tuneerclixlogix** [comment]
Yes @FabienLavocat On both Android and iOS

**Comment by tuneerclixlogix** [comment]
@codlab With beta 0.2.6 ?
https://github.com/voxeet/voxeet-uxkit-reactnative/tree/beta/0.2.6
Or i just call the VoxeetSDK.defaultVideo(true); ?

**Comment by codlab** [comment]
the startVideo() and stopVideo() are available in the (and upward) `0.2.11-beta9`

the defaultVideo(true/false) is already available in previous versions

**Comment by tuneerclixlogix** [comment]
Thanks @codlab , I will try this and will update

**Comment by tuneerclixlogix** [comment]
Thanks @codlab  It's working perfect.
