### ISSUE TITLE
setTelecomMode not working on iOS

### ISSUE THREAD

**Issue by tuneerclixlogix** [voxeet/voxeet-uxkit-reactnative#27]
@FabienLavocat 
I used your commit https://github.com/voxeet/voxeet-uxkit-reactnative/pull/20/commits/c1fec2ef65d1d6f5c37b89d2e8f7f337d3b31f02
and did all the changes from this commit, its working fine on android when i end the call from other side it gets disconnected on the other side as well. But its not working with iOS

**Comment by FabienLavocat** [comment]
@Comanga @vjard Is the telecomMode still implemented in the UXKit for iOS?
https://github.com/voxeet/voxeet-uxkit-reactnative/pull/20/files#diff-f34675648bda4a7f436ea18466aa2f8c46d4474832c96d65974b62b500428c4f

https://github.com/voxeet/voxeet-uxkit-ios/blob/master/VoxeetUXKit/Code/Controllers/VTUXConferenceController.swift#L24

**Comment by vjard** [comment]
Hello @FabienLavocat and @tuneerclixlogix,
We have just released a new UXKit 1.4.6 version which will fix the telecom issue. Will be available in the next release.

**Comment by FabienLavocat** [comment]
Merci @vjard !

**Comment by codlab** [comment]
Should be available, closing this ticket :)
