### ISSUE TITLE
iOS build failing with develop branch

### ISSUE THREAD

**Issue by tuneerclixlogix** [voxeet/voxeet-uxkit-reactnative#32]
For iOS I am not able to build the app with the develop branch
"react-native": "0.63.3"
"@voxeet/react-native-voxeet-conferencekit": "git://github.com/voxeet/voxeet-uxkit-reactnative.git#develop"
"@voxeet/react-native-voxeet-firebase": "^2.0.2"
![image](https://user-images.githubusercontent.com/72122766/118081566-3bf32e00-b3d9-11eb-980a-fed7e539a78c.png)

**Comment by codlab** [comment]
Did you properly installed the pods ?

**Comment by tuneerclixlogix** [comment]
Yes, I also tried after reinstalling the pods

**Comment by tuneerclixlogix** [comment]
@codlab Recently i was facing issues with few pods of low deployment target so I added this in podfile 
post_install do |installer|
    installer.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
     end
    end
   end
This changes the deployment target for all pods. What should be the target for voxeet ? I will set that and will try with that version.

**Comment by tuneerclixlogix** [comment]
@codlab The build is failing with the develop branch, once i reinstalled with master branch it worked fine and the build was successful

**Comment by codlab** [comment]
Make sure to be using Xcode Version 12.5 (12E262)

**Comment by charleston10** [comment]
> @codlab The build is failing with the develop branch, once i reinstalled with master branch it worked fine and the build was successful

I`ve same problem

Can you put your pod File?
What do you believe may have been the problem?

**Comment by codlab** [comment]
You can find its content here : https://github.com/voxeet/voxeet-uxkit-reactnative-testapp/blob/master/ios/Podfile

Notice the lock file as well at https://github.com/voxeet/voxeet-uxkit-reactnative-testapp/blob/master/ios/Podfile.lock

make sure that when you installed the latest develop commit (or for the future, the latest release which will have all these), you upgraded the local pods repository

**Comment by tuneerclixlogix** [comment]
My Xcode version is 12.3 can that be an issue ? 
I will upgrade it today and then try with your podfile.

**Comment by charleston10** [comment]
I solved problem

I had to update the RN's library, because 21 days ago a patch was released to support for Xcode 12.5 and Swift 5.4.
Or can manually add the lib (https://github.com/voxeet/voxeet-sdk-ios/releases/tag/v3.1.5)

**Comment by codlab** [comment]
Closing this ticket since it's only related to Xcode + react-native compatibility (hopefully, one day Xcode's tools will have an dev experience as smooth as the gradle integration, until then this kind of issues will arise each time we need to bump our iOS SDK implementation). Please open a new ticket if something else happens
