### ISSUE TITLE
-[NSNull _fastCStringContents:]: unrecognized selector sent to instance 0x1eb639ee0

### ISSUE THREAD

**Issue by tuneerclixlogix** [voxeet/voxeet-uxkit-reactnative#35]
@codlab @FabienLavocat 
Our users are recently facing the below crash on iOS , this is when the installation is with the develop branch
-[NSNull _fastCStringContents:]: unrecognized selector sent to instance 0x1eb639ee0
![image](https://user-images.githubusercontent.com/72122766/120181491-c38aca80-c22a-11eb-9e3e-ba094e99f9d3.png)

**Comment by codlab** [comment]
What are your connect() arguments?

**Comment by tuneerclixlogix** [comment]
@codlab 
```
{
          externalId: user_id,
          name: firstName,
          avatarUrl: photos[0],
        }
```

**Comment by codlab** [comment]
What are the possible values of each of those variables?

**Comment by tuneerclixlogix** [comment]
The possible values are 
user_id: string
name: string
avatarUrl: string (AWS s3 bucket url)

**Comment by codlab** [comment]
@vjard can you check this, seems a regression in the SDK itself

**Comment by vjard** [comment]
@tuneerclixlogix Cannot reproduce it on develop branch with the following code: 
```
import { VoxeetSDK, ConferenceUser } from "@voxeet/react-native-voxeet-conferencekit";

const user = new ConferenceUser("18", "Vincent", "");

VoxeetSDK.connect(user)

...
```

Are you sure that values are string on client side?

**Comment by vjard** [comment]
@tuneerclixlogix Merge request has been approved, should works on develop branch now. Waiting your feedback before closing this ticket.

**Comment by tuneerclixlogix** [comment]
Thanks @vjard @codlab , 
if it happened with null or undefined then i will also apply checks for these at application side, can i send the blank string if there is any null or undefined value in avtarUrl ?

**Comment by vjard** [comment]
@tuneerclixlogix Yes you can. :)
But I've fixed the problem on Objective-C side, so it will not happen anymore, even with null or undefined.

**Comment by tuneerclixlogix** [comment]
Thanks @vjard
