### ISSUE TITLE
Got error "dependency were found, but they required a higher minimum deployment target"

### ISSUE THREAD

**Issue by hungkoala** [voxeet/voxeet-uxkit-reactnative#41]
**Describe the bug**

Got error "dependency were found, but they required a higher minimum deployment target" when running ``` pod install ```

https://lh3.googleusercontent.com/pw/AM-JKLW0wyHS1z7CG8_2T1MZ0RJj9ooBPygI9Pes4y6rq1ZFVNyJFzvXsjQ3mJ2NLfM2RO0S92AO_y2VO4GoDvZDSb3adv9SfsK2jmSWlnN37j29gWBDs2J81cWVfDEpsXen4XvIYxbeEKwpIt-hoZ5D9-WU=w1802-h800-no?authuser=0

**Expected Behaviour**

should install successfully  

**Steps to Reproduce the Problem**

  1. create new react native project 
  2. install 'voxeet-uxkit-reactnative'
  3. cd ios 
  4. run command 'pod install'

**Minimalistic code (recommended)** 
      https://github.com/hungkoala/chat

**Specifications**

  - Platform: Big sur
  - Swift: Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)
               Target: x86_64-apple-darwin20.5.0
 - Xcode:  Version 12.5.1 (12E507)

**Comment by FabienLavocat** [comment]
Hi @hungkoala,

Could you please update your project and Podfile to support iOS 11 and later. See our [Supported Environments](https://docs.dolby.io/interactivity/docs/overview-supported-environments).
Here is a [Sample Application](https://github.com/voxeet/voxeet-uxkit-reactnative-testapp) that's using the React Native UXKit and its [PodFile](https://github.com/voxeet/voxeet-uxkit-reactnative-testapp/blob/master/ios/Podfile).

Thanks,
Fabien

**Comment by hungkoala** [comment]
after updating IOS 11 on the Podfile, it works
Thanks
