### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by livindead** [voxeet/voxeet-uxkit-reactnative#5]
**Describe the bug**
After installation and linking when trying to run an empty project when compiling, an error occurs
react-native init AwesomeProject
npm install @voxeet/react-native-voxeet-conferencekit --save
react-native link @voxeet/react-native-voxeet-conferencekit
react-native run-ios

`

info CompileC /Users/light/workflow/react/Awe/ios/build/Awe/Build/Intermediates.noindex/RNVoxeetConferencekit.build/Debug-iphonesimulator/RNVoxeetConferencekit.build/Objects-normal/x86_64/RNVoxeetConferencekit.o /Users/light/workflow/react/Awe/node_modules/@voxeet/react-native-voxeet-conferencekit/ios/RNVoxeetConferencekit/RNVoxeetConferencekit.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target: RNVoxeetConferencekit)
    cd /Users/light/workflow/react/Awe/node_modules/@voxeet/react-native-voxeet-conferencekit/ios
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu11 -fobjc-arc -fobjc-weak -fmodules -fmodules-cache-path=/Users/light/workflow/react/Awe/ios/build/Awe/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/light/workflow/react/Awe/ios/build/Awe/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=9.0 -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -Wunguarded-availability -fobjc-abi-version=2 -fobjc-legacy-dispatch -index-store-path /Users/light/workflow/react/Awe/ios/build/Awe/Index/DataStore -iquote /Users/light/workflow/react/Awe/ios/build/Awe/Build/Intermediates.noindex/RNVoxeetConferencekit.build/Debug-iphonesimulator/RNVoxeetConferencekit.build/RNVoxeetConferencekit-generated-files.hmap -I/Users/light/workflow/react/Awe/ios/build/Awe/Build/Intermediates.noindex/RNVoxeetConferencekit.build/Debug-iphonesimulator/RNVoxeetConferencekit.build/RNVoxeetConferencekit-own-target-headers.hmap -I/Users/light/workflow/react/Awe/ios/build/Awe/Build/Intermediates.noindex/RNVoxeetConferencekit.build/Debug-iphonesimulator/RNVoxeetConferencekit.build/RNVoxeetConferencekit-all-target-headers.hmap -iquote /Users/light/workflow/react/Awe/ios/build/Awe/Build/Intermediates.noindex/RNVoxeetConferencekit.build/Debug-iphonesimulator/RNVoxeetConferencekit.build/RNVoxeetConferencekit-project-headers.hmap -I/Users/light/workflow/react/Awe/ios/build/Awe/Build/Products/Debug-iphonesimulator/include -I/Users/light/workflow/react/Awe/ios/build/Awe/Build/Intermediates.noindex/RNVoxeetConferencekit.build/Debug-iphonesimulator/RNVoxeetConferencekit.build/DerivedSources-normal/x86_64 -I/Users/light/workflow/react/Awe/ios/build/Awe/Build/Intermediates.noindex/RNVoxeetConferencekit.build/Debug-iphonesimulator/RNVoxeetConferencekit.build/DerivedSources/x86_64 -I/Users/light/workflow/react/Awe/ios/build/Awe/Build/Intermediates.noindex/RNVoxeetConferencekit.build/Debug-iphonesimulator/RNVoxeetConferencekit.build/DerivedSources -F/Users/light/workflow/react/Awe/ios/build/Awe/Build/Products/Debug-iphonesimulator -F/Users/light/workflow/react/Awe/node_modules/@voxeet/react-native-voxeet-conferencekit/ios/Carthage/Build/iOS -MMD -MT dependencies -MF /Users/light/workflow/react/Awe/ios/build/Awe/Build/Intermediates.noindex/RNVoxeetConferencekit.build/Debug-iphonesimulator/RNVoxeetConferencekit.build/Objects-normal/x86_64/RNVoxeetConferencekit.d --serialize-diagnostics /Users/light/workflow/react/Awe/ios/build/Awe/Build/Intermediates.noindex/RNVoxeetConferencekit.build/Debug-iphonesimulator/RNVoxeetConferencekit.build/Objects-normal/x86_64/RNVoxeetConferencekit.dia -c /Users/light/workflow/react/Awe/node_modules/@voxeet/react-native-voxeet-conferencekit/ios/RNVoxeetConferencekit/RNVoxeetConferencekit.m -o /Users/light/workflow/react/Awe/ios/build/Awe/Build/Intermediates.noindex/RNVoxeetConferencekit.build/Debug-iphonesimulator/RNVoxeetConferencekit.build/Objects-normal/x86_64/RNVoxeetConferencekit.o

info /Users/light/workflow/react/Awe/node_modules/@voxeet/react-native-voxeet-conferencekit/ios/RNVoxeetConferencekit/RNVoxeetConferencekit.m:33:9: error: use of undeclared identifier 'VoxeetSDK'

info 
        VoxeetSDK.shared.callKit = YES;

info         ^

info 

info /Users/light/workflow/react/Awe/node_modules/@voxeet/react-native-voxeet-conferencekit/ios/RNVoxeetConferencekit/RNVoxeetConferencekit.m:35:10: error: use of undeclared identifier 'VoxeetSDK'

info 

info         [VoxeetSDK.shared initializeWithConsumerKey:consumerKey consumerSecret:consumerSecret userInfo:nil connectSession:YES];
         ^

info /Users/light/workflow/react/Awe/node_modules/@voxeet/react-native-voxeet-conferencekit/ios/RNVoxeetConferencekit/RNVoxeetConferencekit.m

info :

info 46

info :9: error

info : use of undeclared identifier 'VoxeetSDK'
        VoxeetSDK.shared.callKit = NO;
        ^

info /Users/light/workflow/react/Awe/node_modules/@voxeet/react-native-voxeet-conferencekit/ios/RNVoxeetConferencekit/RNVoxeetConferencekit.m:47:10: error: use of undeclared identifier 'VoxeetSDK'

info         [VoxeetSDK.shared initializeWithAccessToken:accessToken userInfo:nil refreshTokenClosure:^(void (^closure)(NSString *)) {
         ^

info /Users/light/workflow/react/Awe/node_modules/@voxeet/react-native-voxeet-conferencekit/ios/RNVoxeetConferencekit/RNVoxeetConferencekit.m:68:9: error: 

info use of undeclared identifier 'VTUser'

info         VTUser *user = [[VTUser alloc] initWithExternalID:externalID name:name avatarURL:avatarURL];
        ^

info /Users/light/workflow/react/Awe/node_modules/@voxeet/react-native-voxeet-conferencekit/ios/RNVoxeetConferencekit/RNVoxeetConferencekit.m:68:17: error: use of undeclared identifier 'user'

info         VTUser *user = [[VTUser alloc] initWithExternalID:externalID name:name avatarURL:avatarURL];
                ^

info /Users/light/workflow/react/Awe/node_modules/@voxeet/react-native-voxeet-conferencekit/ios/RNVoxeetConferencekit/RNVoxeetConferencekit.m:68:26: error: use of undeclared identifier 'VTUser'

info         VTUser *user = [[VTUser alloc] initWithExternalID:externalID name:name avatarURL:avatarURL];
info 

info                          ^

info 

info /Users/light/workflow/react/Awe/node_modules/@voxeet/react-native-voxeet-conferencekit/ios/RNVoxeetConferencekit/RNVoxeetConferencekit.m:70:11: error

info : 

info use of undeclared identifier 'VoxeetSDK'

info 

info         [[VoxeetSDK.shared session] connectWithUser:user completion:^(NSError *error) {
info 

          ^

info 

info /Users/light/workflow/react/Awe/node_modules/@voxeet/react-native-voxeet-conferencekit/ios/RNVoxeetConferencekit/RNVoxeetConferencekit.m:84:11: 

info error: use of undeclared identifier 'VoxeetSDK'

info         [[VoxeetSDK.shared session] disconnectWithCompletion:^(NSError *error) {
          ^

info /Users/light/workflow/react/Awe/node_modules/@voxeet/react-native-voxeet-conferencekit/ios/RNVoxeetConferencekit/RNVoxeetConferencekit.m:116:11: error: 

info use of undeclared identifier 'VoxeetSDK'
        [[VoxeetSDK.shared conference] createWithParameters:nativeOptions success:^(NSDictionary<NSString *,id> *response) {

info 

info           ^
info 

info 

info /Users/light/workflow/react/Awe/node_modules/@voxeet/react-native-voxeet-conferencekit/ios/RNVoxeetConferencekit/RNVoxeetConferencekit.m:138:22: error

info : use of undeclared identifier 'VoxeetSDK'
        BOOL video = VoxeetSDK.shared.conference.defaultVideo;

info 

info                      ^

info /Users/light/workflow/react/Awe/node_modules/@voxeet/react-native-voxeet-conferencekit/ios/RNVoxeetConferencekit/RNVoxeetConferencekit.m:139:11: error: 

info use of undeclared identifier 'VoxeetSDK'
        [[VoxeetSDK.shared conference] joinWithConferenceID:conferenceID video:video userInfo:nativeOptions success:^(NSDictionary<NSString *,id> *response) {
          ^

info /Users/light/workflow/react/Awe/node_modules/@voxeet/react-native-voxeet-conferencekit/ios/RNVoxeetConferencekit/RNVoxeetConferencekit.m:151:11: error: 

info use of undeclared identifier 'VoxeetSDK'
        [[VoxeetSDK.shared conference] leaveWithCompletion:^(NSError *error) {

          ^

info /Users/light/workflow/react/Awe/node_modules/@voxeet/react-native-voxeet-conferencekit/ios/RNVoxeetConferencekit/RNVoxeetConferencekit.m:173:11: error: 

info use of undeclared identifier 'VoxeetSDK'

info         [[VoxeetSDK.shared conference] inviteWithConferenceID:conferenceID externalIDs:userIDs completion:^(NSError *error) {

info 

info           ^

info 

info /Users/light/workflow/react/Awe/node_modules/@voxeet/react-native-voxeet-conferencekit/ios/RNVoxeetConferencekit/RNVoxeetConferencekit.m:188:11: error: 

info use of undeclared identifier 'VoxeetSDK'
        [[VoxeetSDK.shared conference] broadcastWithMessage:message completion:^(NSError *error) {
          ^

info /Users/light/workflow/react/Awe/node_modules/@voxeet/react-native-voxeet-conferencekit/ios/RNVoxeetConferencekit/RNVoxeetConferencekit.m

info :

info 208

info :

info 12

info :

info  

info error

info : 

info use of undeclared identifier 'VoxeetSDK'

info 

info         [[[VoxeetSDK shared] conference] setDefaultBuiltInSpeaker:enable];

           ^

info /Users/light/workflow/react/Awe/node_modules/@voxeet/react-native-voxeet-conferencekit/ios/RNVoxeetConferencekit/RNVoxeetConferencekit.m:215:12: 

info error: use of undeclared identifier 'VoxeetSDK'
        [[[VoxeetSDK shared] conference] setDefaultVideo:enable];
           ^

info /Users/light/workflow/react/Awe/node_modules/@voxeet/react-native-voxeet-conferencekit/ios/RNVoxeetConferencekit/RNVoxeetConferencekit.m:270:25: error: use of undeclared identifier 'VoxeetSDK'

info         BOOL isLogIn = (VoxeetSDK.shared.session.state == VTSessionStateConnected);
                        ^
/Users/light/workflow/react/Awe/node_modules/@voxeet/react-native-voxeet-conferencekit/ios/RNVoxeetConferencekit/RNVoxeetConferencekit.m:270:59: error: 

info use of undeclared identifier 'VTSessionStateConnected'

info 

info         BOOL isLogIn = (VoxeetSDK.shared.session.state == VTSessionStateConnected);

info 

info                                                           ^

info fatal error

info : too many errors emitted, stopping now [-ferror-limit=]

info 20

info  error

info s

info  generated

info .

info 

error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening Awe.xcodeproj

2019-05-08 13:05:42.930 xcodebuild[5101:134349] [MT] PluginLoading: Required plug-in compatibility UUID 72F7D751-F810-43B8-A53F-1F1DFD74FC54 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2019-05-08 13:05:42.936 xcodebuild[5101:134349] Failed to load plugin at: /Users/light/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin, skipping.  Reason for failure: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
** BUILD FAILED **
`

**Comment by FabienLavocat** [comment]
This bug has unfortunately being opened for a while. If you still have issues please reopen a new ticket.
