### ISSUE TITLE
Maven - Error downloading library (host access denied)

### ISSUE THREAD

**Issue by charleston10** [voxeet/voxeet-uxkit-reactnative#54]
**Describe the bug**

Maven occur this error downloading library

```
Host: https://android-sdk.voxeet.com/release

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>NDP6Q6JHGM8Y25GP</RequestId>
<HostId>dWUzEJBOFVHVMuMmcHyFX5YglJ/r+x6lncYVRZkNi6QYa5Lherj7ltVI6SZHg5BqEq5WRGTbgKk=</HostId>
</Error>
```

**Expected Behaviour**

download lib normally

**Steps to Reproduce the Problem**

I followed the documentation ([link](https://github.com/voxeet/voxeet-uxkit-reactnative))

  1. Add `maven { url "https://android-sdk.voxeet.com/release" }` in android on `allprojects.repositories`
  2. Click in Sync gradle 

**Minimalistic code (recommended)**

project gradle

```
allprojects {
    repositories {
        maven { url "https://android-sdk.voxeet.com/release" }

        google()
        mavenCentral()

        maven { url 'https://jitpack.io' }
        maven { url("$rootDir/../node_modules/react-native/android") }
        maven { url("$rootDir/../node_modules/jsc-android/dist") }
        mavenLocal()

        jcenter()
    }
}
```

**Specifications**

  - Device: Samsumg S10
  - OS: Android 11
  - Platform: Android
  - Version:
     `"@voxeet/react-native-voxeet-conferencekit": "^0.3.0",`

**Comment by codlab** [comment]
The above error is normally what you can expect when calling directly https://android-sdk.voxeet.com/release. Can you post the full sync logs you got?

Also, it may be possible that the presence of jcenter() is raising this due it's invalidity (I haven't experienced this in the past but maybe that its failure is forcing the chain to check the other urls, thus creating the issue)

**Comment by charleston10** [comment]
I managed to make it work
the order of the dependencies' download repositories were influencing when I was able to consult the maven file
the file was like this

**Gradle Project**
```
buildscript {
    ext {
        kotlin_version = '1.4.10'
        buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
        googlePlayServicesAuthVersion = "16.0.1"
        supportLibVersion = "29.0.0"
        voxeetSdkVersion = "1.4.12"
        mediaSdkVersion = "0.8.2"
    }
    repositories {
        google()
        mavenCentral()
        maven { url "https://maven.fabric.io/public" }
    }

    dependencies {
        classpath('com.android.tools.build:gradle:4.0.2')
        classpath("com.google.gms:google-services:4.3.10")
        classpath("io.fabric.tools:gradle:1.31.0")
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.31"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven { url("$rootDir/../node_modules/react-native/android") }
        maven { url("$rootDir/../node_modules/jsc-android/dist") }
        jcenter()
        maven { url "https://android-sdk.voxeet.com/release" }
        mavenLocal()
    }
}

```
