### ISSUE TITLE
Swift compiler error

### ISSUE THREAD

**Issue by charleston10** [voxeet/voxeet-uxkit-reactnative#59]
**Describe the bug**

Build failed
I updated my mac and also xcode now the project keeps giving error when trying to build

Maybe I need to do a new configuration, can someone help me with this case?

![image](https://user-images.githubusercontent.com/3097207/152539446-138c54f7-4e36-4ba7-8a77-144084cc773e.png)

**Expected Behaviour**

Build success

**Steps to Reproduce the Problem**

Xcode -> Product -> Build

**Specifications**

macOS Monterey 12.2
XCode 13.1 | 13.2 | 13.2.1
Swfit 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)
react-native-voxeet-conferencekit 0.3.0
-- Dependency pod voxeet-uxkit-ios 1.6.0

**Comment by codal-mpawar** [comment]
@FabienLavocat we are facing the same issue. Can you please let us know when we expect the update?
Same specifications as @charleston10 mentioned.
<img width="1221" alt="Screenshot 2022-03-01 at 3 05 45 PM" src="https://user-images.githubusercontent.com/46340921/156143462-e021d545-ba56-4883-8cfd-b186cecbc706.png">
?

**Comment by harpalCodal** [comment]
@FabienLavocat any update for latest iPhone os support ?

**Comment by FabienLavocat** [comment]
Hi @codal-mpawar, the pull request #63 will fix the compatibility issue with the most recent version of Xcode.

**Comment by codal-mpawar** [comment]
@FabienLavocat Can you please let us know when we expect the updated SDK?

**Comment by FabienLavocat** [comment]
The UXKit [0.3.1](https://github.com/voxeet/voxeet-uxkit-reactnative/releases/tag/v0.3.1) has been released on [NPM.JS](https://www.npmjs.com/package/@voxeet/react-native-voxeet-conferencekit/v/0.3.1).

**Comment by codal-mpawar** [comment]
@FabienLavocat **pod install error.**
We getting this error.
Current deployment version 11.0 and we try 11.0 11.2, 11.2 and up to 13.0 and currently we use swift version 5.0 and we try 5.5.1 and 5.5.2. 
So can you please guide us on how we resolve this issue or issue from your side?

<img width="1075" alt="Screenshot 2022-03-10 at 5 15 11 PM" src="https://user-images.githubusercontent.com/46340921/157655385-7f5a575b-441e-4b0c-b6d2-c9fa92920818.png">
