### ISSUE TITLE
[Android] VoxeetSDK.join doesn't resolve or reject promise

### ISSUE THREAD

**Issue by AlexanderPodlesniyQs** [voxeet/voxeet-uxkit-reactnative#7]
VoxeetSDK.join function returns promise which is never resolved or rejected.

Debugging says that this part of code is actually executed:

````
VoxeetSDK.conference()
                    .join(conferenceId)
                    .then((PromiseExec<Boolean, Object>) (result, solver) -> {
                        promise.resolve(result);

                        checkStartVideo();
                    })
                    .error(promise::reject);
````
But it's never get to "then" or "error" part. Even after conference is closed.

**Comment by codlab** [comment]
Please follow the given template when creating a new issue.

What is the version of the plugin you're using?

**Comment by codlab** [comment]
This should be fixed using the mapped Conference instead of the pure Conference instance
