### ISSUE TITLE
The iOS build failed on app center.

### ISSUE THREAD

**Issue by codal-mpawar** [voxeet/voxeet-uxkit-reactnative#73]
@codlab @FabienLavocat 

The iOS build failed on app center.

**The following build commands failed:
	CompileSwift normal arm64 (in target 'VoxeetUXKit' from project 'Pods')
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'VoxeetUXKit' from project 'Pods')**

**Expected Behaviour**

The build wan not failed on any platform.

**Specifications**
Xcode: 13.4
node version ^16
0.3.2 latest version of your library.

**Comment by codal-mpawar** [comment]
@FabienLavocat @codlab @j12y Any update?

**Comment by codal-mpawar** [comment]
@FabienLavocat @codlab any update?

**Comment by FabienLavocat** [comment]
Could you please provide a more complete log file.
