### ISSUE TITLE
How to turn off Video Recording button?

### ISSUE THREAD

**Issue by hungkoala** [voxeet/voxeet-uxkit-reactnative#75]
![Screenshot_2023-02-22-17-35-16-601_care zoop bewell](https://user-images.githubusercontent.com/2076651/220597296-51bba3b9-9a35-48f1-bed4-d63d930522e7.jpg)

![Screenshot_2023-02-22-17-36-16-898_com android systemui](https://user-images.githubusercontent.com/2076651/220597848-69639f56-52fa-4cef-a10b-e76c1d8615eb.jpg)

**Comment by codal-mpawar** [comment]
@FabienLavocat Any update?

**Comment by codal-mpawar** [comment]
@hungkoala 
Click on below link and set setScreenShareEnabled(false) then working fine and after then you can create patch file
https://github.com/voxeet/voxeet-uxkit-reactnative/blob/dd46d795f559496e4bbe6963ff5700a6af044597/android/src/main/java/com/voxeet/reactnative/manifests/RNVoxeetManifestComponent.java#L73

**Comment by FabienLavocat** [comment]
@hungkoala I would recommend to clone this repository into your project and follow the tip from @codal-mpawar. For Android, change the value from `true` to `false`:
https://github.com/voxeet/voxeet-uxkit-reactnative/blob/dd46d795f559496e4bbe6963ff5700a6af044597/android/src/main/java/com/voxeet/reactnative/manifests/RNVoxeetManifestComponent.java#L73
```java
VoxeetToolkit.instance().getConferenceToolkit().setScreenShareEnabled(false); 
```

For iOS, in the [create function](https://github.com/voxeet/voxeet-uxkit-reactnative/blob/dd46d795f559496e4bbe6963ff5700a6af044597/ios/RNVoxeetConferencekit/RNVoxeetConferencekit.m#L112-L143), I would add the following line to disable the button:
```objectivec
VoxeetUXKit.shared.conferenceController.configuration.actionBar.displayScreenShare = true;
```

**Comment by hungkoala** [comment]
perfect
