### ISSUE TITLE
Android: Conference error and notification title issue

### ISSUE THREAD

**Issue by codal-mpawar** [voxeet/voxeet-uxkit-reactnative#76]
Getting below error when starting video calling from android. After getting an error call disconnect automatically.

1st issue: 
 LOG  <========== VoxeetSDK.join Error : Error: ../../../../../../../dvc_wrapper/dvmc/dvc_library.cc:179: Initialize failed in DVC_Initialize(&dvc_config, "4.3.6") with status Failed to open the specified file ==========>

2nd issue: 
We are seeing this notification. So, how we remove this notification. it's display every time **change me**
![Screenshot_20230307-131706_Gallery](https://user-images.githubusercontent.com/46340921/223357897-118d8c34-8192-494c-b484-8efcac75cd2b.jpg)

**Expected Behaviour**

Every time get success to connect video calls.

**Steps to Reproduce the Problem**

  1. Open the app
  2. Start the video call process
  3. You can see the video call kit and ge
  4. After 2 to 3 seconds call disconnects automatically.

```javascript
await VoxeetSDK.join(conference.conferenceId, {
                user: {
                    type: UserType.USER
                }
            })
                .then(async (res) => {
                    console.log(`<========== VoxeetSDK.join success ==========>`);
                    //Send video call notification to reciver
                    const participant = new ConferenceParticipant(
                        recieverData.sub,
                        recieverData.preferred_username,
                        recieverData.picture
                    );
                    await VoxeetSDK.invite(conference.conferenceId, [participant]);
                })
                .catch((err) => {
                    console.log(`<========== VoxeetSDK.join Error : ${err} ==========>`);
                });
```

**Specifications**
  - Device: Samsung galaxy A20
  - OS: Android 11
  - Platform: Android 
  - Version:
     - "@voxeet/react-native-voxeet-conferencekit": "^0.40.0"
    - "@voxeet/react-native-voxeet-firebase": "^2.2.0"
    - "react": "16.13.1"
    - "react-native": "0.64.2"

**Comment by codlab** [comment]
1. What are the full logs when this is happening ?

2. You need to change it via a custom string resource in your android/app/src/main/res/values/strings.xml and creating a new string node with android:name="voxeet_foreground_content_title" and a value which would fit your own use case description. Preferably, please also create values for the other languages as well

**Comment by codal-mpawar** [comment]
@codlab Can we change with javascript code instead of static text?

**Comment by codal-mpawar** [comment]
@codlab @FabienLavocat android device logs

[voxeet_video_call_log.pdf](https://github.com/voxeet/voxeet-uxkit-reactnative/files/10908842/voxeet_video_call_log.pdf)

**Comment by codlab** [comment]
Regarding the text, this is currently only possible via a static definition in the resources

Also the issue happening seems to be related to the bundle not shipping one the assets used. Is it a production crash ?

**Comment by codal-mpawar** [comment]
@codlab No it's not production crash currently it's in development.
Please check the recordings. In pdf i will replace my bundle id and in some api's as well for security.


https://user-images.githubusercontent.com/46340921/223427982-cd2f3352-5e5a-4a83-81b3-2344f61a347d.mp4

**Comment by codlab** [comment]
ok so you're using an apk and not an app bundle, the name in the logs was weird but you replacing it by a placeholder makes more sense after reading you.

From what I can see from the package name you forgot to change, it may be because of a upper case vs lower case issue. Can you make sure from Android studio that the file exists, the logs indicates that the absolute path is expected to be /data/user/0/__APP_BUNDLE_/cache/model.dnr.

Since you're in development, the app should be debuggable, letting Android Studio give you the ability to explore your app's own folders

**Comment by codal-mpawar** [comment]
please share the mail id we will share full logs with the correct app bundle.

**Comment by codal-mpawar** [comment]
@FabienLavocat ^

**Comment by codal-mpawar** [comment]
@codlab 
It's working fine once both users are online. So closing this issue currently.

**Comment by codal-mpawar** [comment]
It's not working. please share your email.

**Comment by codlab** [comment]
You can use kevin.leperf -at- dolby.com

**Comment by codal-mpawar** [comment]
@codlab We will share android logs soon.

**Comment by codal-mpawar** [comment]
@codlab @FabienLavocat please check your mail

**Comment by codal-mpawar** [comment]
@codlab @FabienLavocat **dvc_log_file.txt** This file was deleted once we clear the cache and after that video call not working. currently, we are not deleting this file from the cache and video calls working fine, so for now closing this issue.
