### ISSUE TITLE
[Android] ConferenceUserUtil.toMap fails if user.getStatus() is null 

### ISSUE THREAD

**Issue by AlexanderPodlesniyQs** [voxeet/voxeet-uxkit-reactnative#8]
**ConferenceUserUtil.toMap fails if user.getStatus() is null**

In ConferenceUserUtil class toMap function throws exception if user status is null.
This line produces it:
````
map.putString("conferenceStatus", user.getStatus().name());
````

**Expected Behaviour**

Handle user status is null

After fixes for this [issue](https://github.com/voxeet/voxeet-uxkit-reactnative/issues/7) VoxeetSDK.join promise always fails because of this problem.

**Specifications**
    Plugin version: 0.1.26
    Device: [Android Emulator Pixel 3XL]
    OS: [Android 10 API 29]

**Comment by codlab** [comment]
The last commit 1bb81f9 will fix the issue. A fix is scheduled for the SDK to send the proper non null expected value
