### ISSUE TITLE
Different behavior of call window on Android and iOS devices

### ISSUE THREAD

**Issue by AlexanderPodlesniyQs** [voxeet/voxeet-uxkit-reactnative#9]
Call window* is shown on different actions on Android and iOS devices.

* Android
Call window is shown after VoxeetSDK.join function call.
* iOS
Call window is shown after VoxeetSDK.create function call.

In general it's not a problem but:
- it's unclear behavior on different platforms
- **on iOS, after VoxeetSDK.create function call, call window is shown with all buttons disabled. If VoxeetSDK.join function is not called it leads to app hanging - you have no way to close call window**.

**Expected Behaviour**

Show call window on VoxeetSDK.join function call or provide a possibility to close call window.

**Steps to Reproduce the Problem**
````
await VoxeetSDK.initializeToken(<token>);
await VoxeetSDK.connect({
  name: <name>,
  avatarUrl: <url>,
  externalId: <id>,
});
const conference = await VoxeetSDK.create({ alias: <alias> });
// await for VoxeetSDK.join hangs on Android in version 0.1.26. Bugfix has not been released yet.
VoxeetSDK.join(conference.conferenceId)
````

*Call window - overlay window which is shown after call start, where you can choose camera, mute microphone etc.

**Specifications**

  - Plugin version: 0.1.26
  - Device: [Iphonex, Android Emulator Pixel 3XL]
  - OS: [iOS13.3.1, Android 10 API 29]
  - Platform: [iOS, Android]

**Comment by VTCoco** [comment]
For most cases, you need to call the `create` **and** `join` methods (`create` method only generate a conference for 60s, if nobody enters, it will be destroyed).
Do you have a special utility of creating a conference without joining it? I'm trying first to understand your workflow.

**Comment by damithsynapsys** [comment]
@AlexanderPodlesniyQs @VTCoco hey guys if you have API document for this can you share with me, please.

**Comment by FabienLavocat** [comment]
https://github.com/voxeet/voxeet-uxkit-reactnative#usage
